require "user.plugins.lsp"
require "user.plugins.cmp"
require "user.plugins.telescope"
require "user.plugins.treesitter"
require "user.plugins.gps"
require "user.plugins.bufferline"
require "user.plugins.closetags"
require "user.plugins.colorizer"
require "user.plugins.comment"
-- require "user.plugins.dashboard"
require "user.plugins.gitsigns"
require "user.plugins.indent"
require "user.plugins.lualine"
-- require "user.plugins.nvim_tree"
require "user.plugins.neotree"
require "user.plugins.telescope"
require "user.plugins.numb"
-- require "user.plugins.which_key"
require "user.plugins.legendary"
require "user.plugins.zen_mode"
require "user.plugins.twilight"
require "user.plugins.alpha"